/*
 * The 15 platform services/modules — single source of truth for the
 * modules list on the home page and the /services/[slug] detail pages.
 */

export type Service = {
  no: string;
  slug: string;
  title: string;
  summary: string;
  intro: string;
  features: string[];
};

export const services: Service[] = [
  {
    no: "01",
    slug: "member-client-management",
    title: "Member & Client Management",
    summary: "Member registration, KYC, profiles, beneficiaries, and lifecycle management.",
    intro: "Onboard and manage every SACCO member from a single registry — from first registration through KYC verification, profile updates, and account closure. Built for cooperative membership, with support for individual and group members.",
    features: [
      "Member registration and onboarding",
      "KYC capture and document management",
      "Member profiles with contact, ID, and photo",
      "Beneficiary and next-of-kin records",
      "Member search, listing, and filtering",
      "Membership lifecycle (active, dormant, closed)",
      "Member transfer between branches",
      "Amharic and English profile data",
    ],
  },
  {
    no: "02",
    slug: "savings-management",
    title: "Savings Management",
    summary: "Savings products, deposits, withdrawals, interest, and account management.",
    intro: "Configure unlimited savings products and manage member savings end to end — mandatory, voluntary, fixed, and goal-based. Every deposit and withdrawal is captured, posted to the ledger, and fully traceable.",
    features: [
      "Configurable products (mandatory, voluntary, fixed, target)",
      "Account opening, approval, and closure",
      "Deposits and withdrawals",
      "Interest accrual and posting",
      "Charges, fees, and waivers",
      "Account holds and blocks",
      "Savings statements in ETB",
      "Complete transaction history",
    ],
  },
  {
    no: "03",
    slug: "loan-management",
    title: "Loan Management",
    summary: "Loan products, applications, approval, disbursement, and portfolio management.",
    intro: "Run the complete loan lifecycle — from product design and application through appraisal, approval, and disbursement. Purpose-built for cooperative lending with both group and individual loans.",
    features: [
      "Configurable loan products",
      "Loan application and appraisal",
      "Multi-level approval (maker-checker)",
      "Disbursement to cash, bank, or mobile money",
      "Collateral and guarantor tracking",
      "Portfolio and PAR monitoring",
      "Write-off and restructuring",
      "Full loan account history",
    ],
  },
  {
    no: "04",
    slug: "loan-repayment-amortization",
    title: "Loan Repayment & Amortization",
    summary: "Repayment schedules, amortization, prepayments, arrears, and collections.",
    intro: "Automatically generate amortization schedules and process repayments with precision. Track arrears, handle prepayments, and keep every member's balance accurate to the birr.",
    features: [
      "Automatic amortization schedule generation",
      "Reducing-balance and flat-rate methods",
      "Repayment processing (full and partial)",
      "Prepayment and early settlement",
      "Grace periods and moratoriums",
      "Arrears and overdue tracking",
      "Rescheduling and restructuring",
      "Repayment receipts and history",
    ],
  },
  {
    no: "05",
    slug: "share-dividend-management",
    title: "Share & Dividend Management",
    summary: "Share capital, purchases, transfers, dividend declaration, and payouts.",
    intro: "Manage member share capital and the full dividend cycle — the heart of the cooperative model. Record share purchases, transfers, and redemptions, then declare and distribute dividends transparently.",
    features: [
      "Configurable share products",
      "Share purchase and allocation",
      "Share transfer and redemption",
      "Share certificate issuance",
      "Dividend declaration and calculation",
      "Dividend payout to members",
      "Share capital ledger in ETB",
      "Dividend history per member",
    ],
  },
  {
    no: "06",
    slug: "interest-penalty-management",
    title: "Interest & Penalty Management",
    summary: "Interest rates, accrual, penalty rules, calculation, and posting.",
    intro: "Define and automate all interest and penalty logic across savings and loans. Set rates, schedule accruals, and apply penalties consistently — with a full audit trail of every rate change.",
    features: [
      "Interest rate setup per product",
      "Savings interest accrual and posting",
      "Loan interest calculation",
      "Overdue penalty rules and calculation",
      "Penalty and interest waivers",
      "Automated accrual runs",
      "Rate change history",
      "Posting to the correct ledger accounts",
    ],
  },
  {
    no: "07",
    slug: "accounting-general-ledger",
    title: "Accounting & General Ledger",
    summary: "Chart of accounts, double-entry journals, statements, and period management.",
    intro: "A full double-entry accounting engine sits under every transaction. Every disbursement, deposit, share, and dividend produces a balanced, immutable, traceable journal — turning the platform into a true core banking system, not just a loan-and-savings tracker.",
    features: [
      "Configurable chart of accounts (46 seeded SACCO accounts)",
      "Automated double-entry journals for every transaction",
      "Manual journals and reversals",
      "Accounting periods with close and reopen",
      "Opening balance migration",
      "Product-to-GL account mapping",
      "Trial balance, balance sheet, income statement, cash flow",
      "ETB precision with Ethiopian-calendar periods",
    ],
  },
  {
    no: "08",
    slug: "financial-reporting-analytics",
    title: "Financial Reporting & Analytics",
    summary: "Financial reports, regulatory reporting, dashboards, KPIs, and analytics.",
    intro: "Turn ledger data into decisions. Generate financial and regulatory reports on demand, and monitor portfolio health through live dashboards and analytics — all exportable for the board, auditors, and the NBE.",
    features: [
      "Financial statements and operational reports",
      "NBE regulatory reporting",
      "Live dashboards and KPIs",
      "Portfolio analytics (PAR, growth, trends)",
      "Savings and membership analytics",
      "Loan performance analysis",
      "Scheduled report generation",
      "Export to PDF, Excel, and CSV",
    ],
  },
  {
    no: "09",
    slug: "approval-workflow-delegation",
    title: "Approval Workflow & Delegation",
    summary: "Approval matrix, maker-checker, multi-level routing, delegation, and escalation.",
    intro: "Enforce cooperative governance with a configurable approval matrix. Route transactions by type and amount, require maker-checker sign-off, delegate authority during absences, and escalate automatically when service levels are breached.",
    features: [
      "Configurable approval matrix",
      "Maker-checker on sensitive actions",
      "Multi-level and amount-based routing",
      "Authority delegation (leave / absence cover)",
      "Delegation limits and history",
      "SLA-based escalation",
      "Approval task assignment",
      "Full approval audit trail",
    ],
  },
  {
    no: "10",
    slug: "branch-region-staff-management",
    title: "Branch, Region & Staff Management",
    summary: "Branches, regions, staff, organizational hierarchy, and data scoping.",
    intro: "Model your entire cooperative structure — head office, regions, and branches — with staff assigned to each. Data is automatically scoped so every branch sees only its own members, savings, and loans, while head office sees the consolidated picture.",
    features: [
      "Branch and region setup",
      "Organizational hierarchy",
      "Staff and employee records",
      "Staff-to-branch assignment",
      "Branch-level data scoping and security",
      "Branch-level accounting and closure",
      "Per-branch reporting",
      "Consolidated head-office view",
    ],
  },
  {
    no: "11",
    slug: "payment-integration",
    title: "Payment Integration",
    summary: "EthSwitch, Telebirr, CBE Birr, reconciliation, and ISO 20022 messaging.",
    intro: "Connect the SACCO to Ethiopia's payment rails. Members deposit, repay, and withdraw through mobile money and switch networks, with automatic reconciliation and standards-based messaging.",
    features: [
      "EthSwitch integration",
      "Telebirr mobile money",
      "CBE Birr",
      "ISO 20022 messaging",
      "Automatic transaction reconciliation",
      "Payment routing by channel",
      "Mobile-money float management",
      "Real-time payment status",
    ],
  },
  {
    no: "12",
    slug: "security-access-control",
    title: "Security & Access Control",
    summary: "Authentication, authorization, MFA, permissions, and role-based access control.",
    intro: "Protect member data and funds with bank-grade security. Every action is authenticated, authorized, and governed by fine-grained, role-based permissions — with strong password policy and encrypted transport throughout.",
    features: [
      "JWT authentication and session management",
      "Role-based access control (RBAC)",
      "Fine-grained permissions per action",
      "Multi-factor authentication (MFA)",
      "Password policy and account lockout",
      "Encrypted transport (TLS 1.3)",
      "Secure credential storage (Argon2id)",
      "Branch-scoped authorization",
    ],
  },
  {
    no: "13",
    slug: "audit-compliance",
    title: "Audit & Compliance",
    summary: "Audit logs, compliance monitoring, regulatory reporting, and risk management.",
    intro: "Every state-changing action across every module is captured in an immutable, branch-scoped audit trail — who did what, when, and with what result. Built to satisfy NBE supervision, internal control, and dispute resolution.",
    features: [
      "Immutable, append-only audit log across all modules",
      "Who / what / when / before / after capture",
      "Maker-checker traceability",
      "Branch-scoped audit access",
      "Search, filter, and export",
      "Configurable retention",
      "NBE-aligned compliance reporting",
      "Tamper-evident logging",
    ],
  },
  {
    no: "14",
    slug: "system-administration",
    title: "System Administration",
    summary: "Configuration, product setup, scheduler, notifications, localization, and maintenance.",
    intro: "Run the platform without a developer. Configure products and parameters, schedule automated jobs, manage notifications and language, and keep the system healthy with backups and maintenance tools.",
    features: [
      "Global and tenant configuration",
      "Product and parameter setup",
      "Scheduled and end-of-day jobs",
      "Notifications (SMS, email, in-app)",
      "Multi-language (Amharic, English)",
      "Ethiopian calendar and ETB formatting",
      "Theme and branding customization",
      "Backups and maintenance",
    ],
  },
  {
    no: "15",
    slug: "digital-channels",
    title: "Digital Channels",
    summary: "Mobile app, web portal, USSD, agent banking, self-service, and member engagement.",
    intro: "Meet members where they are. Give them access through mobile, web, and USSD, extend reach with agent banking, and cut branch load with self-service — driving engagement across urban and rural Ethiopia.",
    features: [
      "Member mobile app",
      "Web self-service portal",
      "USSD for basic phones",
      "Agent banking",
      "Self-service transactions and statements",
      "Balance and loan enquiries",
      "Notifications and alerts",
      "Member engagement tools",
    ],
  },
];

export const getService = (slug: string) => services.find((s) => s.slug === slug);
